steps:
  - name: 'hashicorp/terraform:1.6'
    id: 'Terraform Init'
    entrypoint: 'sh'
    dir: "${_APPLICATION_DIRECTORY}"
    args:
      - '-c'
      - |
          terraform init -backend-config="bucket=${_BUCKET_NAME}" -backend-config="prefix=${_APPLICATION_DIRECTORY}/${_ENVIRONMENT}"

  - name: hashicorp/terraform:1.6
    id: 'Terraform Plan'
    entrypoint: 'sh'
    dir: "${_APPLICATION_DIRECTORY}"
    args:
      - '-c'
      - |
         terraform plan -var-file="tfvars/variables.${_ENVIRONMENT}.tfvars"

  - name: hashicorp/terraform:1.6
    id: 'Terraform Apply'
    entrypoint: 'sh'
    dir: "${_APPLICATION_DIRECTORY}"
    args:
      - '-c'
      - |
         terraform apply


logsBucket: 'gs://bkt-cb-log-bkt'
options:
 logging: GCS_ONLY

substitutions: 
   _APPLICATION_DIRECTORY: "bootstrap"
   _ENVIRONMENT: "shared"
   _BUCKET_NAME: "bkt-cb-log-bkt"
   