steps:
  - id: 'Terraform Init'
    name: "hashicorp/terraform:1.2.9"
    entrypoint: 'sh'
    dir: "${_APPLICATION_DIRECTORY}"
    args:
      - '-c'
      - |
        terraform init

  - id: 'Terraform Plan'
    name: "hashicorp/terraform:1.2.9"
    entrypoint: 'sh'
    dir: "${_APPLICATION_DIRECTORY}"
    args:
      - '-c'
      - |
        terraform plan

  - id: 'Terraform Apply'
    name: "${_TF_IMAGE}"
    entrypoint: 'sh'
    dir: "${_APPLICATION_DIRECTORY}"
    args:
      - '-c'
      - |
        terraform apply -auto-approve

substitutions:
  _APPLICATION_DIRECTORY: "path/to/your/application"
  _TF_IMAGE: "hashicorp/terraform:1.2.9"

timeout: "1200s"
