name: tf-prod-workflow-apply
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud builds submit --config=cicd/tf-apply-template.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # Valid logging setting

substitutions: 
  _ORG_ROOT: "cicd"
  _TF_DIRECTORY: "cicd/66slz"
  _APPLICATION_DIRECTORY: "cicd"
  _ENVIRONMENT: "shared"
  TF_BACKEND_PREFIX: "bkt-b-tfstate-e842"