steps:
  - id: 'Check Branch'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" != feature/* ]]; then
            echo "Not the main branch, skipping build."
            exit 1
          fi

  - id: 'TF Init'
    name: $_TF_IMAGE
    entrypoint: 'sh'
    dir: $_APPLICATION_DIRECTORY
    args:
      - '-c'
      - |
         if [[ -z "$_PLATFORM" ]]; then
           terraform init -backend-config="bucket=${_GCS_BUCKET}" -backend-config="prefix=${_APPLICATION_DIRECTORY}/${_ENVIRONMENT}"  
         else
           pushd $_APPLICATION_DIRECTORY/$_PLATFORM
           terraform init -backend-config="bucket=${_GCS_BUCKET}" -backend-config="prefix=${_APPLICATION_DIRECTORY}/$_PLATFORM/${_ENVIRONMENT}"  
           popd
         fi

         

  - id: 'Checkov'
    name: 'python:3.10' 
    entrypoint: 'sh'
    dir: '$_APPLICATION_DIRECTORY'
    args:
      - '-c'
      - |
          echo "Installing Checkov"
          pip install --no-cache-dir checkov
          echo "Running Checkov scan"
          checkov -d . --framework terraform --download-external-modules false --skip-check ${_CHECKOV_SKIP_CHECKS}

  - id: 'Terraform format'
    name: $_TF_IMAGE
    entrypoint: 'sh'
    dir: $_APPLICATION_DIRECTORY
    args:
      - '-c'
      - |
         terraform fmt -recursive	

  - id: 'Terraform Validate'
    name: $_TF_IMAGE
    entrypoint: 'sh'
    dir: $_APPLICATION_DIRECTORY
    args:
      - '-c'
      - |
         terraform validate -no-color

  - id: 'Terraform Plan'
    name: $_TF_IMAGE
    entrypoint: 'sh'
    dir: $_APPLICATION_DIRECTORY
    args:
      - '-c'
      - |
         terraform plan -var-file="tfvars/variables.$_ENVIRONMENT.tfvars" -out=tf.plan
         echo "Terraform plan created successfully."

logsBucket: 'gs://bkt-cb-log-bkt'
options:
  logging: GCS_ONLY

substitutions:
  _APPLICATION_DIRECTORY: "bootstrap"
  _TF_IMAGE: "hashicorp/terraform:1.2.9"
  _ENVIRONMENT: "shared"
  _GCS_BUCKET: "bkt-cb-log-bkt"
  _CHECKOV_SKIP_CHECKS: ""
  _PLATFORM: "iam/"